# Generated by Django 5.1.6 on 2025-05-05 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geo',
            old_name='lon',
            new_name='lng',
        ),
        migrations.AlterField(
            model_name='geo',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='core.query'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membershipPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_memberships', to='core.membershipplan'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='query',
            name='membershipPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.membershipplan'),
        ),
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PastMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membershipStart', models.DateTimeField(blank=True, null=True)),
                ('membershipEnd', models.DateTimeField(blank=True, null=True)),
                ('membershipDay', models.IntegerField(default=0)),
                ('querySum', models.IntegerField(default=0)),
                ('membershipPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_memberships', to='core.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PostMembership',
        ),
    ]
